///////////////////////////////////////////////////////////
//  CollectionDescription.cs
//  Implementation of the Class CollectionDescription
//  Generated by Enterprise Architect
//  Created on:      19-mar-2018 23.02.24
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

using projekatRES3;
namespace projekatRES3 {
	public class CollectionDescription {

		private int dataset;
		private int id;
        public projekatRES3.HistoricalCollection m_HistoricalCollection = new HistoricalCollection();
        public DateTime timeStamp;

		public CollectionDescription(){

		}

		~CollectionDescription(){

		}

		public int Dataset{
			get{
				return dataset;
			}
			set{
				dataset = value;
			}
		}

		public int ID{
			get{
				return id;
			}
			set{
				id = value;
			}
		}

        public override string ToString()
        {
            return "ID: " + ID + ", DataSet: " + Dataset + ", Code: " + m_HistoricalCollection.m_WorkerProperty[0].Code + "Value: "+ m_HistoricalCollection.m_WorkerProperty[0].WorkerValue + "\nTimeStamp: " + timeStamp ;
        }

    }//end CollectionDescription

}//end namespace projekatRES3