///////////////////////////////////////////////////////////
//  HistoricalCollection.cs
//  Implementation of the Class HistoricalCollection
//  Generated by Enterprise Architect
//  Created on:      19-mar-2018 23.02.24
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

using projekatRES3;
namespace projekatRES3 {
	public class HistoricalCollection {

		public projekatRES3.WorkerProperty[] m_WorkerProperty = new WorkerProperty[1]; //provjeri ovo 1

		public HistoricalCollection(){

		}

		~HistoricalCollection(){

		}

	}//end HistoricalCollection

}//end namespace projekatRES3