///////////////////////////////////////////////////////////
//  ILoadBalancer.cs
//  Implementation of the Interface ILoadBalancer
//  Generated by Enterprise Architect
//  Created on:      19-mar-2018 23.02.24
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace projekatRES3 {
	public interface ILoadBalancer  {

	}//end ILoadBalancer

}//end namespace projekatRES3