///////////////////////////////////////////////////////////
//  LoadBalancer.cs
//  Implementation of the Class LoadBalancer
//  Generated by Enterprise Architect
//  Created on:      19-mar-2018 23.02.24
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using projekatRES3;

namespace projekatRES3 {
	public class LoadBalancer : ILoadBalancer {

		public List<Worker> m_Worker;

		public LoadBalancer(){

		}

		~LoadBalancer(){

		}

	}//end LoadBalancer

}//end namespace projekatRES3