///////////////////////////////////////////////////////////
//  WorkerProperty.cs
//  Implementation of the Class WorkerProperty
//  Generated by Enterprise Architect
//  Created on:      19-mar-2018 23.02.25
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace projekatRES3 {
	public class WorkerProperty {

		private Code code;
		private int historicalValue;

		public WorkerProperty(){

		}

		~WorkerProperty(){

		}

		public Code Code{
			get{
				return code;
			}
			set{
				code = value;
			}
		}

		public int HistoricalValue{
			get{
				return historicalValue;
			}
			set{
				historicalValue = value;
			}
		}

	}//end WorkerProperty

}//end namespace projekatRES3