///////////////////////////////////////////////////////////
//  Writer.cs
//  Implementation of the Class Writer
//  Generated by Enterprise Architect
//  Created on:      19-mar-2018 23.02.25
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using projekatRES3;

namespace projekatRES3 {
	public class Writer : IWriter {

		public projekatRES3.LoadBalancer m_LoadBalancer;

		public Writer(){

		}

		~Writer(){

		}

	}//end Writer

}//end namespace projekatRES3