///////////////////////////////////////////////////////////
//  ILoadBalancer.cs
//  Implementation of the Interface ILoadBalancer
//  Generated by Enterprise Architect
//  Created on:      19-mar-2018 23.02.24
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace projekatRES3 {
	public interface ILoadBalancerContractvv  {
        bool ReceiveFromWriter(Code code, int value);
        //metoda za provjeru da li je worker upaljen ili ugasen
        //metoda za slanje workeru i raspodjelu posla
        bool SendToWorker();
        bool ReceiveTurnOnOff(bool turnOn);
	}//end ILoadBalancer

}//end namespace projekatRES3