///////////////////////////////////////////////////////////
//  IWorker.cs
//  Implementation of the Interface IWorker
//  Generated by Enterprise Architect
//  Created on:      19-mar-2018 23.02.24
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace projekatRES3 {
	public interface IWorker  {
        bool ReceiveFromLoadBalancer(Code code, int value);
        bool CompareCodeValue(Code code, int value);//ValidationCheck
        bool Deadband(CollectionDescription collectionDescription);
        bool Serialization(CollectionDescription collectionDescription);
        bool Serializer(CollectionDescription collectionDescription);
    }//end IWorker

}//end namespace projekatRES3