///////////////////////////////////////////////////////////
//  IWriter.cs
//  Implementation of the Interface IWriter
//  Generated by Enterprise Architect
//  Created on:      19-mar-2018 23.02.24
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ServiceModel;

namespace projekatRES3 {
    [ServiceContract]
	public interface ILBContract  {
        [OperationContract]
        bool WriteToLoadBalancer(Code code, int value);
        [OperationContract]
        bool RequestForTurnOnOff(bool turnOn,string workerName);
	}//end IWriter

}//end namespace projekatRES3