///////////////////////////////////////////////////////////
//  Code.cs
//  Implementation of the Enumeration Code
//  Generated by Enterprise Architect
//  Created on:      22-May-2018 6:28:16 PM
//  Original author: Dejana
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace projekatRES3 {
	public enum Code : int {

		CODE_ANALOG,
		CODE_DIGITAL,
		CODE_CUSTOM,
		CODE_LIMITSET,
		CODE_SINGLENOE,
		CODE_MULTIPLENODE,
		CODE_CONSUMER,
		CODE_SOURCE

	}//end Code

}//end namespace projekatRES3