///////////////////////////////////////////////////////////
//  CollectionDescription.cs
//  Implementation of the Class CollectionDescription
//  Generated by Enterprise Architect
//  Created on:      22-May-2018 6:28:16 PM
//  Original author: Dejana
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using projekatRES3;
namespace projekatRES3 {
	public class CollectionDescription {

		private int dataset;
		private int id;
		public projekatRES3.HistoricalCollection m_HistoricalCollection;

		public CollectionDescription(){

		}

		~CollectionDescription(){

		}

		public int Dataset{
			get{
				return dataset;
			}
			set{
				dataset = value;
			}
		}

		public int ID{
			get{
				return id;
			}
			set{
				id = value;
			}
		}

	}//end CollectionDescription

}//end namespace projekatRES3