///////////////////////////////////////////////////////////
//  HistoricalCollection.cs
//  Implementation of the Class HistoricalCollection
//  Generated by Enterprise Architect
//  Created on:      22-May-2018 6:28:16 PM
//  Original author: Dejana
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using projekatRES3;
namespace projekatRES3 {
	public class HistoricalCollection {

		public projekatRES3.WorkerProperty m_WorkerProperty;

		public HistoricalCollection(){

		}

		~HistoricalCollection(){

		}

	}//end HistoricalCollection

}//end namespace projekatRES3