///////////////////////////////////////////////////////////
//  ILoadBalancer.cs
//  Implementation of the Interface ILoadBalancer
//  Generated by Enterprise Architect
//  Created on:      22-May-2018 6:28:16 PM
//  Original author: Dejana
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using projekatRES3;


namespace projekatRES3 {
	public interface ILoadBalancer  {

	}//end ILoadBalancer

}//end namespace projekatRES3