///////////////////////////////////////////////////////////
//  IReader.cs
//  Implementation of the Interface IReader
//  Generated by Enterprise Architect
//  Created on:      22-May-2018 6:28:16 PM
//  Original author: Dejana
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using projekatRES3;


namespace projekatRES3 {
	public interface IReader  {

	}//end IReader

}//end namespace projekatRES3