///////////////////////////////////////////////////////////
//  IWorker.cs
//  Implementation of the Interface IWorker
//  Generated by Enterprise Architect
//  Created on:      22-May-2018 6:28:16 PM
//  Original author: Dejana
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace projekatRES3 {
	public interface IWorker  {

	}//end IWorker

}//end namespace projekatRES3