///////////////////////////////////////////////////////////
//  IWriter.cs
//  Implementation of the Interface IWriter
//  Generated by Enterprise Architect
//  Created on:      22-May-2018 6:28:16 PM
//  Original author: Dejana
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace projekatRES3 {
	public interface IWriter  {

	}//end IWriter

}//end namespace projekatRES3