///////////////////////////////////////////////////////////
//  LoadBalancer.cs
//  Implementation of the Class LoadBalancer
//  Generated by Enterprise Architect
//  Created on:      22-May-2018 6:28:16 PM
//  Original author: Dejana
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using projekatRES3;
namespace projekatRES3 {
	public class LoadBalancer : ILoadBalancer {

		public List<Worker> m_Worker;

		public LoadBalancer(){

		}

		~LoadBalancer(){

		}

	}//end LoadBalancer

}//end namespace projekatRES3