///////////////////////////////////////////////////////////
//  Reader.cs
//  Implementation of the Class Reader
//  Generated by Enterprise Architect
//  Created on:      22-May-2018 6:28:17 PM
//  Original author: Dejana
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using projekatRES3;
namespace projekatRES3 {
	public class Reader : IReader {

		public projekatRES3.Worker m_Worker;

		public Reader(){

		}

		~Reader(){

		}

	}//end Reader

}//end namespace projekatRES3