///////////////////////////////////////////////////////////
//  Worker.cs
//  Implementation of the Class Worker
//  Generated by Enterprise Architect
//  Created on:      22-May-2018 6:28:17 PM
//  Original author: Dejana
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using projekatRES3;
namespace projekatRES3 {
	public class Worker : IWorker {

		public projekatRES3.CollectionDescription m_CollectionDescription;

		public Worker(){

		}

		~Worker(){

		}

	}//end Worker

}//end namespace projekatRES3