///////////////////////////////////////////////////////////
//  Writer.cs
//  Implementation of the Class Writer
//  Generated by Enterprise Architect
//  Created on:      22-May-2018 6:28:17 PM
//  Original author: Dejana
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using projekatRES3;
namespace projekatRES3 {
	public class Writer : IWriter {

		public projekatRES3.LoadBalancer m_LoadBalancer;

		public Writer(){

		}

		~Writer(){

		}

	}//end Writer

}//end namespace projekatRES3