///////////////////////////////////////////////////////////
//  IReader.cs
//  Implementation of the Interface IReader
//  Generated by Enterprise Architect
//  Created on:      19-mar-2018 23.02.24
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ServiceModel;

namespace projekatRES3 {
    [ServiceContract]
	public interface IReader  {
        [OperationContract]
        List<CollectionDescription> GetDataSetForTimePeriod(Code c, DateTime satrtTime, DateTime endTime);

        [OperationContract]
        List<CollectionDescription> Deserialization(int dataSet);

    }//end IReader

}//end namespace projekatRES3